on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: exions/merge-upstream@v1
        with:
          upstream: godvsdeity/ngx_http_auth_basic_ldap_module
